### ISSUE TITLE
8/31 과제

### ISSUE THREAD

**Issue by yoosojeong** [yoosojeong/python_directory#1]
- 함수 변수 복수개 입력받는 방법 연습
- 소수를 구하는 함수 만들기
-  리스트를 전달하면 리스트의 항목중 짝수번째 숫자만 더하는 함수
  ex)
list = [1, 2, 4, 7, 10, 13] 
result = sum_even(list)
result 는 22

- 리스트를 전달하면 리스트의 항목중 홀수번째는 빼고 짝수번째는 더하는 함수
list = [1, 2, 4, 7, 10, 13] 
result = sum_minus(list)
result 는 -1 + 2 - 4 + 7 - 10 + 13

- 생년월일을 입력하면 내년 생일까지 남은 일수를 돌려주는 함수
days = count_next_birthday("2010-10-05")

**Comment by cheddars** [comment]
매일매일 커밋하는거!! 잘 하고 있는거죠? ㅎㅎㅎ

**Comment by cheddars** [comment]
git 사용법 관련해서 이글 한번 쭈~욱 읽어보면 도움 될거 같아요!!
모두 이해하기 힘들더라도 너무 걱정은 말구요
https://nolboo.kim/blog/2013/10/06/github-for-beginner/

**Comment by yoosojeong** [comment]
넹넹~~
